# Generated by Django 5.1.4 on 2026-04-28 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_seed_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='channel',
            field=models.CharField(choices=[('sms', 'SMS'), ('email', 'Email')], default='sms', max_length=8),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
