# Generated by Django 5.1.4 on 2026-05-02 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_seed_kumasi_submetros'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailotp',
            new_name='accounts_em_user_id_214752_idx',
            old_name='accounts_em_user_id_created_idx',
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
