# Generated by Django 5.1.4 on 2026-04-26 20:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_regions'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('septic', 'Septic tank'), ('soak_pit', 'Soak pit / cesspit'), ('industrial', 'Industrial liquid waste')], max_length=20)),
                ('volume_tier', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10)),
                ('pickup_lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_lng', models.DecimalField(decimal_places=7, max_digits=10)),
                ('pickup_address', models.CharField(blank=True, max_length=300)),
                ('notes', models.TextField(blank=True)),
                ('quote_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote_base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quote_distance_km', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8)),
                ('quote_distance_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('quote_tier_fee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('assigned', 'Assigned'), ('accepted', 'Accepted'), ('en_route', 'En route'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('unfulfilled', 'Unfulfilled')], default='pending', max_length=16)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('en_route_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_requests', to='drivers.driver')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='accounts.region')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('expires_at', models.DateTimeField()),
                ('outcome', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('timeout', 'Timeout'), ('superseded', 'Superseded')], default='pending', max_length=12)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='drivers.driver')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='requests_app.servicerequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['status'], name='requests_ap_status_fa6e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['customer', '-created_at'], name='requests_ap_custome_60b2fd_idx'),
        ),
        migrations.AddIndex(
            model_name='servicerequest',
            index=models.Index(fields=['driver', '-created_at'], name='requests_ap_driver__d7dce4_idx'),
        ),
        migrations.AddIndex(
            model_name='requestassignment',
            index=models.Index(fields=['request', '-created_at'], name='requests_ap_request_282046_idx'),
        ),
    ]
