# Generated by Django 5.1.4 on 2026-05-02 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='gate_fits_truck',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Not sure')], default='', max_length=8),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='gate_photo',
            field=models.ImageField(blank=True, null=True, upload_to='requests/gate/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='is_overflowing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='last_emptied',
            field=models.CharField(blank=True, choices=[('lt_6m', 'Less than 6 months'), ('6_12m', '6–12 months'), ('1_2y', '1–2 years'), ('gt_2y', '2 years+'), ('never', 'Never'), ('unknown', 'Unknown')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='preferred_time',
            field=models.CharField(blank=True, choices=[('asap', 'ASAP'), ('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='someone_on_site',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tank_cover_photo',
            field=models.ImageField(blank=True, null=True, upload_to='requests/tank/'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tank_cover_state',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('closed_accessible', 'Closed but accessible'), ('sealed', 'Sealed (needs breaking)'), ('unknown', 'Unknown')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='tank_location',
            field=models.CharField(blank=True, choices=[('front', 'Front of house'), ('side', 'Side of house'), ('back', 'Back of house'), ('under_driveway', 'Under driveway'), ('other', 'Other')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='truck_parking_distance',
            field=models.CharField(blank=True, choices=[('at_gate', 'At the gate'), ('5_10', '5–10 m'), ('10_20', '10–20 m'), ('20_plus', '20 m+')], default='', max_length=8),
        ),
    ]
