# Generated by Django 5.1.4 on 2026-05-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_assignment_batch_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='receipt_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='receipt_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
