# Generated by Django 5.1.4 on 2026-05-28 11:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_driver_online_since'),
        ('fleets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='driver',
            index=models.Index(fields=['status', 'is_online'], name='driver_status_online_idx'),
        ),
    ]
