# Generated by Django 5.1.4 on 2026-04-26 20:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_seed_regions'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_fee_min', models.DecimalField(decimal_places=2, default=Decimal('30'), max_digits=10)),
                ('base_fee_max', models.DecimalField(decimal_places=2, default=Decimal('150'), max_digits=10)),
                ('distance_rate_per_km', models.DecimalField(decimal_places=2, default=Decimal('3'), max_digits=10)),
                ('tier_small_fee', models.DecimalField(decimal_places=2, default=Decimal('50'), max_digits=10)),
                ('tier_medium_fee', models.DecimalField(decimal_places=2, default=Decimal('100'), max_digits=10)),
                ('tier_large_fee', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=10)),
                ('commission_pct', models.DecimalField(decimal_places=2, default=Decimal('15'), max_digits=5)),
                ('matching_radius_km', models.PositiveIntegerField(default=15)),
                ('accept_window_seconds', models.PositiveIntegerField(default=60)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='accounts.region')),
            ],
            options={
                'verbose_name': 'Pricing config',
                'verbose_name_plural': 'Pricing configs',
            },
        ),
    ]
